"""empty message

Revision ID: 785252f50ea4
Revises: 965f7235a16d
Create Date: 2022-11-05 00:44:55.470342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785252f50ea4'
down_revision = '965f7235a16d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Agenda',
    sa.Column('id_agenda', sa.Integer(), nullable=False),
    sa.Column('dia', sa.DateTime(), nullable=False),
    sa.Column('quarto_1', sa.Boolean(), nullable=True),
    sa.Column('quarto_2', sa.Boolean(), nullable=True),
    sa.Column('quarto_3', sa.Boolean(), nullable=True),
    sa.Column('quarto_4', sa.Boolean(), nullable=True),
    sa.Column('quarto_5', sa.Boolean(), nullable=True),
    sa.Column('quarto_6', sa.Boolean(), nullable=True),
    sa.Column('quarto_7', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_agenda')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Agenda')
    # ### end Alembic commands ###
