"""empty message

Revision ID: 79aba2c64c16
Revises: 785252f50ea4
Create Date: 2022-11-08 18:01:57.468094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79aba2c64c16'
down_revision = '785252f50ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Quarto', sa.Column('preco', sa.Float(), nullable=True))
    op.drop_column('Quarto', 'preço')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Quarto', sa.Column('preço', sa.FLOAT(), nullable=True))
    op.drop_column('Quarto', 'preco')
    # ### end Alembic commands ###
