"""empty message

Revision ID: 7e422d505e4f
Revises: 
Create Date: 2022-11-04 12:31:48.753785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e422d505e4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hospedagem',
    sa.Column('id_hospedagem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_hospedagem')
    )
    op.create_table('Hospede',
    sa.Column('id_hospede', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_hospede')
    )
    op.create_table('Quarto',
    sa.Column('id_quarto', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('andar', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=150), nullable=True),
    sa.Column('preço', sa.Float(), nullable=True),
    sa.Column('custo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_quarto')
    )
    op.create_table('ReservaHospedagem',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ReservaHospedagem')
    op.drop_table('Quarto')
    op.drop_table('Hospede')
    op.drop_table('Hospedagem')
    # ### end Alembic commands ###
