"""empty message

Revision ID: 965f7235a16d
Revises: 
Create Date: 2022-11-05 00:43:25.326310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965f7235a16d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hospede',
    sa.Column('id_hospede', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_hospede'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Quarto',
    sa.Column('id_quarto', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('andar', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=150), nullable=True),
    sa.Column('preço', sa.Float(), nullable=True),
    sa.Column('custo', sa.Float(), nullable=True),
    sa.Column('disponibilidade', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_quarto')
    )
    op.create_table('Hospedagem',
    sa.Column('id_hospedagem', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('quarto_id', sa.Integer(), nullable=True),
    sa.Column('hospede_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospede_id'], ['Hospede.id_hospede'], ),
    sa.ForeignKeyConstraint(['quarto_id'], ['Quarto.id_quarto'], ),
    sa.PrimaryKeyConstraint('id_hospedagem')
    )
    op.create_table('ReservaHospedagem',
    sa.Column('id_reserva_hospedagem', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('quarto_id', sa.Integer(), nullable=True),
    sa.Column('hospede_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospede_id'], ['Hospede.id_hospede'], ),
    sa.ForeignKeyConstraint(['quarto_id'], ['Quarto.id_quarto'], ),
    sa.PrimaryKeyConstraint('id_reserva_hospedagem')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ReservaHospedagem')
    op.drop_table('Hospedagem')
    op.drop_table('Quarto')
    op.drop_table('Hospede')
    # ### end Alembic commands ###
